import knex from '../lib/knex.mjs'


export const project = {
  name: "project",
  columns: [
    // this is autogenerated portion from database data
    //{ name: "id", type: "integer" },
    //{ name: "description", type: "string", length: 4000 },
    // ...
  ],
  links: [
    // manually configured
    { name: "projectdetails", type: "m1", col: "projectDetailId" }, // many to 1
    { name: "projectcontact", type: "1m", col: "refId" }, // 1 to many
    { name: "attachmententity", type: "1m", col: "refId", discriminator: { "type":2 } }, // 1 to many
  ]
}

export const attachmententity = {
  name: "attachmententity",
  columns: [
    // this is autogenerated portion from database data
    //{ name: "id", type: "integer" },
    //{ name: "description", type: "string", length: 4000 },
    // ...
  ],
  links: [
    // manually configured
    { name: "attachment", type: "m1", col: "attachmentId" }, // many to 1
  ]
}

export const attachment = {
  name: "attachment",
  columns: [
    // this is autogenerated portion from database data
    //{ name: "id", type: "integer" },
    //{ name: "description", type: "string", length: 4000 },
    // ...
  ],
  links: [
    // manually configured
    { name: "attachmentversion", type: "1m", col: "attachmentId" }, // many to 1
  ]
}

export const projectDetails = {
  name: "projectdetails",
  columns: [
    // { name: "id", type: "integer" },
    // { name: "text1", type: "string", length: 4000 },
    // ...
  ],
  links: [
    { name: "ProjectDetails", type: "m1", col: "projectDetailId" }, // many to 1
    { name: "ProjectContact", type: "1m", col: "refId" }, // 1 to many
  ]
}
